"""Physics-informed mask training for the HFSS multitask dataset.

This is the second-stage sanity check after the direct black-box surrogate:
the network predicts active-element logits, while per-task complex phases are
generated by the known steering law. This removes the impossible requirement of
learning random per-sample mask labels exactly from target angles alone.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import time
from dataclasses import asdict
from pathlib import Path

import numpy as np
import torch
from torch import nn
from torch.utils.data import DataLoader, WeightedRandomSampler

from train_hfss_surrogate import (
    DEFAULT_DATASET_DIR,
    EPS,
    K_VALUES,
    NUM_ELEMENTS,
    EvalSummary,
    HfssArrayDataset,
    build_features,
    compute_af_metrics,
    hard_gate_from_logits,
    load_split_manifest,
    make_grid,
    safe_mean,
    safe_percentile,
    target_dirs_torch,
    unit_vectors,
    write_csv,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dataset-dir", type=Path, default=DEFAULT_DATASET_DIR)
    parser.add_argument("--out-dir", type=Path, default=None)
    parser.add_argument("--epochs", type=int, default=120)
    parser.add_argument("--batch-size", type=int, default=128)
    parser.add_argument("--hidden", type=int, default=512)
    parser.add_argument("--lr", type=float, default=8.0e-4)
    parser.add_argument("--weight-decay", type=float, default=1.0e-4)
    parser.add_argument("--seed", type=int, default=20260629)
    parser.add_argument("--psll-margin-db", type=float, default=3.0)
    parser.add_argument("--spread-margin-db", type=float, default=5.0)
    parser.add_argument("--binarize-weight", type=float, default=0.02)
    parser.add_argument("--mask-bce-weight", type=float, default=0.02)
    parser.add_argument("--weak-peak-weight", type=float, default=0.02)
    parser.add_argument("--k46-sample-weight", type=float, default=1.0)
    parser.add_argument("--train-eval-every", type=int, default=10)
    parser.add_argument("--device", default="auto", choices=("auto", "cpu", "cuda"))
    return parser.parse_args()


def set_seed(seed: int) -> None:
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def resolve_device(name: str) -> torch.device:
    if name == "cuda":
        return torch.device("cuda")
    if name == "cpu":
        return torch.device("cpu")
    return torch.device("cuda" if torch.cuda.is_available() else "cpu")


class MaskNet(nn.Module):
    def __init__(self, input_dim: int, hidden: int):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, hidden),
            nn.LayerNorm(hidden),
            nn.SiLU(),
            nn.Linear(hidden, hidden),
            nn.LayerNorm(hidden),
            nn.SiLU(),
            nn.Linear(hidden, hidden),
            nn.SiLU(),
            nn.Linear(hidden, NUM_ELEMENTS),
        )

    def forward(self, features: torch.Tensor) -> torch.Tensor:
        return self.net(features)


def gate_from_logits(mask_logits: torch.Tensor, num_active: torch.Tensor, *, hard: bool) -> torch.Tensor:
    if hard:
        gate = torch.zeros_like(mask_logits)
        for i in range(mask_logits.shape[0]):
            k = int(round(float(num_active[i].detach().cpu().item())))
            idx = torch.topk(mask_logits[i], k=k, largest=True).indices
            gate[i, idx] = 1.0
        return gate
    gate = torch.sigmoid(mask_logits)
    gate = gate * (num_active[:, None].clamp_min(1.0) / gate.sum(dim=1, keepdim=True).clamp_min(1.0))
    return gate.clamp(0.0, 1.0)


def steering_weights(
    gate: torch.Tensor,
    targets_deg: torch.Tensor,
    task_valid: torch.Tensor,
    num_active: torch.Tensor,
    positions: torch.Tensor,
) -> torch.Tensor:
    dirs = target_dirs_torch(targets_deg)
    phase = 2.0 * math.pi * torch.einsum("bkd,nd->bkn", dirs, positions)
    steering = torch.exp(1j * phase.to(torch.complex64)).permute(0, 2, 1)
    weights = steering * gate[:, :, None].to(torch.complex64) * task_valid[:, None, :].to(torch.complex64)
    return weights / num_active[:, None, None].clamp_min(1.0).to(torch.complex64)


def physics_metrics_loss(
    weights_complex: torch.Tensor,
    targets_deg: torch.Tensor,
    task_valid: torch.Tensor,
    positions: torch.Tensor,
    grid_dirs: torch.Tensor,
    psll_margin_db: float,
    spread_margin_db: float,
    weak_peak_weight: float,
) -> tuple[torch.Tensor, dict[str, torch.Tensor]]:
    combined = weights_complex.sum(dim=2)
    target_dirs = target_dirs_torch(targets_deg)
    target_steering = torch.exp(
        -1j * (2.0 * math.pi * torch.einsum("bkd,nd->bkn", target_dirs, positions)).to(torch.complex64)
    )
    target_response = torch.einsum("bkn,bn->bk", target_steering, combined)
    target_db = 10.0 * torch.log10(torch.abs(target_response).square().clamp_min(EPS))
    valid_bool = task_valid.bool()
    min_target = target_db.masked_fill(~valid_bool, 1.0e6).min(dim=1).values
    max_target = target_db.masked_fill(~valid_bool, -1.0e6).max(dim=1).values

    grid_phase = 2.0 * math.pi * grid_dirs @ positions.T
    grid_steering = torch.exp(-1j * grid_phase.to(torch.complex64))
    grid_response = combined @ grid_steering.T
    grid_db = 10.0 * torch.log10(torch.abs(grid_response).square().clamp_min(EPS))

    dots = torch.einsum("gd,bkd->bgk", grid_dirs, target_dirs).clamp(-1.0, 1.0)
    dists = torch.rad2deg(torch.acos(dots))
    dists = torch.where(valid_bool[:, None, :], dists, torch.full_like(dists, 999.0))
    side_mask = dists.min(dim=2).values > 8.0
    side_max = grid_db.masked_fill(~side_mask, -1.0e6).max(dim=1).values

    psll_weak = side_max - min_target
    spread = max_target - min_target
    loss = torch.relu(psll_weak + psll_margin_db).square().mean()
    loss = loss + 0.25 * torch.relu(spread - spread_margin_db).square().mean()
    loss = loss - weak_peak_weight * min_target.mean()
    return loss, {
        "psll_weak_db": psll_weak.detach().mean(),
        "weak_peak_db": min_target.detach().mean(),
        "spread_db": spread.detach().mean(),
    }


def train_one_epoch(
    model: nn.Module,
    loader: DataLoader,
    optimizer: torch.optim.Optimizer,
    device: torch.device,
    positions: torch.Tensor,
    grid_dirs: torch.Tensor,
    args: argparse.Namespace,
) -> dict[str, float]:
    model.train()
    totals: dict[str, float] = {}
    total_n = 0
    bce = nn.BCEWithLogitsLoss()
    for batch in loader:
        features = batch["features"].to(device)
        target_mask = batch["mask"].to(device)
        targets_deg = batch["targets_deg"].to(device)
        task_valid = batch["task_valid"].to(device)
        num_active = batch["num_active"].to(device)

        logits = model(features)
        gate = gate_from_logits(logits, num_active, hard=False)
        weights = steering_weights(gate, targets_deg, task_valid, num_active, positions)
        physics_loss, stats = physics_metrics_loss(
            weights,
            targets_deg,
            task_valid,
            positions,
            grid_dirs,
            args.psll_margin_db,
            args.spread_margin_db,
            args.weak_peak_weight,
        )
        bce_loss = bce(logits, target_mask)
        bin_loss = (gate * (1.0 - gate)).mean()
        loss = physics_loss + args.binarize_weight * bin_loss + args.mask_bce_weight * bce_loss

        optimizer.zero_grad(set_to_none=True)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 5.0)
        optimizer.step()

        bs = int(features.shape[0])
        total_n += bs
        for key, value in {
            "loss": loss,
            "physics_loss": physics_loss,
            "bce_loss": bce_loss,
            "bin_loss": bin_loss,
            **stats,
        }.items():
            totals[key] = totals.get(key, 0.0) + float(value.detach().cpu()) * bs
    return {key: value / max(total_n, 1) for key, value in totals.items()}


@torch.no_grad()
def collect_logits(model: nn.Module, dataset: HfssArrayDataset, device: torch.device, batch_size: int) -> tuple[np.ndarray, np.ndarray]:
    loader = DataLoader(dataset, batch_size=batch_size, shuffle=False)
    model.eval()
    idx_chunks: list[np.ndarray] = []
    logit_chunks: list[np.ndarray] = []
    for batch in loader:
        logits = model(batch["features"].to(device))
        idx_chunks.append(batch["index"].numpy())
        logit_chunks.append(logits.cpu().numpy().astype(np.float32))
    idx = np.concatenate(idx_chunks)
    logits = np.concatenate(logit_chunks)
    order = np.argsort(idx)
    return idx[order], logits[order]


def analytic_weights_from_gate(
    gate: np.ndarray,
    arrays: dict[str, np.ndarray],
) -> np.ndarray:
    positions = arrays["positions_lambda"].astype(np.float32)
    targets = arrays["targets_deg"].astype(np.float32)
    task_valid = arrays["task_valid"].astype(bool)
    num_active = arrays["num_active"].astype(np.float32)
    num_samples = gate.shape[0]
    out = np.zeros((num_samples, NUM_ELEMENTS, 6), dtype=np.complex64)
    for i in range(num_samples):
        safe_targets = np.nan_to_num(targets[i], nan=0.0)
        dirs = unit_vectors(safe_targets[:, 0], safe_targets[:, 1])
        phase = 2.0 * np.pi * (dirs @ positions.T)
        steering = np.exp(1j * phase).astype(np.complex64).T
        out[i] = steering * gate[i, :, None].astype(np.complex64) * task_valid[i][None, :]
        out[i] /= max(float(num_active[i]), 1.0)
    return out


def summarize_group(
    split: str,
    k_label: int | str,
    active_label: str,
    idx: np.ndarray,
    eval_arrays: dict[str, np.ndarray | dict[str, np.ndarray]],
) -> EvalSummary:
    teacher = eval_arrays["teacher"]  # type: ignore[assignment]
    model = eval_arrays["model"]  # type: ignore[assignment]
    assert isinstance(teacher, dict) and isinstance(model, dict)
    mask_iou = eval_arrays["mask_iou"][idx]  # type: ignore[index]
    soft_active_error = np.abs(eval_arrays["soft_active"][idx] - eval_arrays["active_ratio"][idx])  # type: ignore[index]
    weight_rmse = eval_arrays["weight_rmse_scaled"][idx]  # type: ignore[index]
    teacher_weak = teacher["target_peak_min_db"][idx]
    model_weak = model["target_peak_min_db"][idx]
    teacher_psll = teacher["psll_to_weakest_peak_db"][idx]
    model_psll = model["psll_to_weakest_peak_db"][idx]
    return EvalSummary(
        split=split,
        k=k_label,
        active_ratio=active_label,
        n=int(idx.size),
        mask_iou_mean=safe_mean(mask_iou),
        soft_active_error_mean=safe_mean(soft_active_error),
        weight_rmse_scaled=safe_mean(weight_rmse),
        teacher_target_peak_min_mean_db=safe_mean(teacher_weak),
        model_target_peak_min_mean_db=safe_mean(model_weak),
        delta_weak_peak_mean_db=safe_mean(model_weak - teacher_weak),
        teacher_psll_weak_mean_db=safe_mean(teacher_psll),
        model_psll_weak_mean_db=safe_mean(model_psll),
        delta_psll_weak_mean_db=safe_mean(model_psll - teacher_psll),
        teacher_psll_weak_p95_db=safe_percentile(teacher_psll, 95),
        model_psll_weak_p95_db=safe_percentile(model_psll, 95),
        teacher_isolation_worst_p05_db=safe_percentile(teacher["isolation_worst_db"][idx], 5),
        model_isolation_worst_p05_db=safe_percentile(model["isolation_worst_db"][idx], 5),
    )


def evaluate(
    model: nn.Module,
    arrays: dict[str, np.ndarray],
    features: np.ndarray,
    splits: dict[str, np.ndarray],
    device: torch.device,
    batch_size: int,
) -> tuple[list[EvalSummary], dict[str, float]]:
    all_idx = np.arange(arrays["k_values"].shape[0], dtype=np.int64)
    dataset = HfssArrayDataset(arrays, features, all_idx)
    _, logits = collect_logits(model, dataset, device, batch_size)
    hard_gate = hard_gate_from_logits(logits, arrays["num_active"].astype(np.float32))
    soft_active = 1.0 / (1.0 + np.exp(-logits))
    soft_active_mean = soft_active.mean(axis=1)
    target_gate = arrays["masks"].astype(np.float32)
    inter = (hard_gate * target_gate).sum(axis=1)
    union = np.maximum(hard_gate + target_gate, 0.0).clip(0.0, 1.0).sum(axis=1)
    mask_iou = inter / np.maximum(union, 1.0)

    model_weights = analytic_weights_from_gate(hard_gate, arrays)
    teacher_weights = arrays["task_weights_real_imag"][..., 0] + 1j * arrays["task_weights_real_imag"][..., 1]
    model_scaled = np.stack([model_weights.real, model_weights.imag], axis=-1) * arrays["num_active"][:, None, None, None]
    teacher_scaled = arrays["task_weights_real_imag"].astype(np.float32) * arrays["num_active"][:, None, None, None]
    valid = arrays["task_valid"][:, None, :, None].astype(np.float32)
    weight_rmse = np.sqrt(((model_scaled - teacher_scaled) ** 2 * valid).sum(axis=(1, 2, 3)) / np.maximum(valid.sum(axis=(1, 2, 3)) * NUM_ELEMENTS * 2, 1.0))

    _, _, eval_grid = make_grid(theta_step=2.0, phi_step=5.0)
    teacher_metrics = compute_af_metrics(
        teacher_weights.astype(np.complex64),
        arrays["targets_deg"].astype(np.float32),
        arrays["task_valid"].astype(np.float32),
        arrays["positions_lambda"].astype(np.float32),
        eval_grid,
    )
    model_metrics = compute_af_metrics(
        model_weights.astype(np.complex64),
        arrays["targets_deg"].astype(np.float32),
        arrays["task_valid"].astype(np.float32),
        arrays["positions_lambda"].astype(np.float32),
        eval_grid,
    )
    eval_arrays: dict[str, np.ndarray | dict[str, np.ndarray]] = {
        "teacher": teacher_metrics,
        "model": model_metrics,
        "mask_iou": mask_iou.astype(np.float32),
        "soft_active": soft_active_mean.astype(np.float32),
        "active_ratio": arrays["active_ratios_requested"].astype(np.float32),
        "weight_rmse_scaled": weight_rmse.astype(np.float32),
    }

    rows: list[EvalSummary] = []
    for split, idx in splits.items():
        rows.append(summarize_group(split, "all", "all", idx, eval_arrays))
        for k in K_VALUES:
            k_idx = idx[arrays["k_values"][idx] == k]
            rows.append(summarize_group(split, k, "all", k_idx, eval_arrays))
            for ar in (0.5, 0.6, 0.7, 0.8, 0.9, 1.0):
                sub = k_idx[np.isclose(arrays["active_ratios_requested"][k_idx], ar)]
                rows.append(summarize_group(split, k, f"{ar:.1f}", sub, eval_arrays))

    test_idx = splits["test"]
    k46 = test_idx[np.isin(arrays["k_values"][test_idx], [4, 6])]
    headline = {
        "test_mask_iou_mean": safe_mean(mask_iou[test_idx]),
        "test_soft_active_error_mean": safe_mean(np.abs(soft_active_mean[test_idx] - arrays["active_ratios_requested"][test_idx])),
        "test_weight_rmse_scaled": safe_mean(weight_rmse[test_idx]),
        "test_delta_psll_weak_mean_db": safe_mean(model_metrics["psll_to_weakest_peak_db"][test_idx] - teacher_metrics["psll_to_weakest_peak_db"][test_idx]),
        "test_delta_weak_peak_mean_db": safe_mean(model_metrics["target_peak_min_db"][test_idx] - teacher_metrics["target_peak_min_db"][test_idx]),
        "test_k46_delta_psll_weak_mean_db": safe_mean(model_metrics["psll_to_weakest_peak_db"][k46] - teacher_metrics["psll_to_weakest_peak_db"][k46]),
        "test_k46_delta_weak_peak_mean_db": safe_mean(model_metrics["target_peak_min_db"][k46] - teacher_metrics["target_peak_min_db"][k46]),
    }
    return rows, headline


def main() -> None:
    args = parse_args()
    set_seed(args.seed)
    device = resolve_device(args.device)
    dataset_dir: Path = args.dataset_dir
    if args.out_dir is None:
        out_dir = dataset_dir / "training_runs" / f"steering_mask_{time.strftime('%Y%m%d_%H%M%S')}"
    else:
        out_dir = args.out_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    arrays_npz = np.load(dataset_dir / "dataset_arrays.npz", allow_pickle=False)
    arrays = {key: arrays_npz[key] for key in arrays_npz.files}
    splits = load_split_manifest(dataset_dir / "training_split_manifest.json")
    features = build_features(
        arrays["k_values"],
        arrays["active_ratios_requested"],
        arrays["targets_deg"],
        arrays["task_valid"],
    )
    train_dataset = HfssArrayDataset(arrays, features, splits["train"])
    if args.k46_sample_weight > 1.0:
        train_idx = splits["train"]
        train_weights = np.ones(train_idx.shape[0], dtype=np.float64)
        train_weights[np.isin(arrays["k_values"][train_idx], [4, 6])] = float(args.k46_sample_weight)
        sampler = WeightedRandomSampler(
            weights=torch.from_numpy(train_weights),
            num_samples=int(train_idx.shape[0]),
            replacement=True,
        )
        loader = DataLoader(train_dataset, batch_size=args.batch_size, sampler=sampler)
    else:
        loader = DataLoader(train_dataset, batch_size=args.batch_size, shuffle=True)
    model = MaskNet(features.shape[1], args.hidden).to(device)
    optimizer = torch.optim.AdamW(model.parameters(), lr=args.lr, weight_decay=args.weight_decay)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=max(args.epochs, 1), eta_min=args.lr * 0.08)
    positions = torch.from_numpy(arrays["positions_lambda"].astype(np.float32)).to(device)
    _, _, train_grid_np = make_grid(theta_step=4.0, phi_step=8.0)
    train_grid = torch.from_numpy(train_grid_np).to(device)

    config = {
        "dataset_dir": str(dataset_dir),
        "out_dir": str(out_dir),
        "device": str(device),
        "feature_dim": int(features.shape[1]),
        "num_train": int(splits["train"].shape[0]),
        "num_val": int(splits["val"].shape[0]),
        "num_test": int(splits["test"].shape[0]),
        "args": {k: str(v) if isinstance(v, Path) else v for k, v in vars(args).items()},
    }
    (out_dir / "run_config.json").write_text(json.dumps(config, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Training steering-mask model on {device}; output={out_dir}")
    print(f"splits train/val/test={len(splits['train'])}/{len(splits['val'])}/{len(splits['test'])}")
    log_rows: list[dict[str, object]] = []
    start = time.time()
    for epoch in range(args.epochs):
        stats = train_one_epoch(model, loader, optimizer, device, positions, train_grid, args)
        scheduler.step()
        row = {"epoch": epoch, "lr": optimizer.param_groups[0]["lr"], **stats}
        log_rows.append(row)
        if epoch == 0 or (epoch + 1) % args.train_eval_every == 0 or epoch + 1 == args.epochs:
            msg = ", ".join(f"{k}={v:.5g}" for k, v in stats.items())
            print(f"epoch {epoch + 1:03d}/{args.epochs}: {msg}")
            write_csv(out_dir / "train_log.csv", log_rows)

    torch.save({"model_state": model.state_dict(), "config": config}, out_dir / "steering_mask_model.pt")
    print("Evaluating steering-mask model...")
    rows, headline = evaluate(model, arrays, features, splits, device, args.batch_size)
    write_csv(out_dir / "eval_summary_by_split_k_active.csv", [asdict(r) for r in rows])
    metrics = {
        "headline": headline,
        "elapsed_s": time.time() - start,
        "outputs": {
            "train_log": str(out_dir / "train_log.csv"),
            "eval_summary": str(out_dir / "eval_summary_by_split_k_active.csv"),
            "model": str(out_dir / "steering_mask_model.pt"),
        },
    }
    (out_dir / "metrics_summary.json").write_text(json.dumps(metrics, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(metrics, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
